<a href="https://colab.research.google.com/github/VanNguyenThiCam/NumPy-for-Data-Science-Beginners/blob/main/C%C3%A1ch_kh%E1%BB%9Fi_t%E1%BA%A1o_m%E1%BA%A3ng_ma_tr%E1%BA%ADn_%C4%91%C6%A1n_gi%E1%BA%A3n_v%C3%A0_%C4%91%E1%BA%B7c_bi%E1%BB%87t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Cách khởi tao ma trận sinh giá trị ngẫu nhiên***

In [2]:
import numpy as np

arr = np.array([0,1,2,3,4])
print(arr)

[0 1 2 3 4]


In [3]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [4]:
arr = np.arange(10,20,2, dtype = float)
print(arr)

[10. 12. 14. 16. 18.]


In [5]:
arr = np.linspace(10,20,5)
print(arr)

[10.  12.5 15.  17.5 20. ]


In [6]:
arr = np.linspace(10,20,5, endpoint = False)
print(arr)

[10. 12. 14. 16. 18.]


In [7]:
arr = np.logspace(10,20, num = 10)
print(arr)

[1.00000000e+10 1.29154967e+11 1.66810054e+12 2.15443469e+13
 2.78255940e+14 3.59381366e+15 4.64158883e+16 5.99484250e+17
 7.74263683e+18 1.00000000e+20]


***Cách khởi tạo ma trận đặc biệt như ma trận 0, ma trận 1***

In [8]:
import numpy as np

np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,2)) #ma trận toàn số 0

array([[0., 0.],
       [0., 0.]])

In [10]:
np.zeros((2,3,4)) #ma trận hiểu theo nghĩa sâu 2, dài 3, rộng 4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((2,2)) #ma trận toàn số 1

array([[1., 1.],
       [1., 1.]])

In [13]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [14]:
np.full((2,2,2),99,dtype = 'int32')

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]], dtype=int32)

In [15]:
arr = np.array([[1,2,3],[4,5,6]])

In [16]:
np.full_like(arr,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [17]:
np.full(arr.shape,4)

array([[4, 4, 4],
       [4, 4, 4]])

In [18]:
np.identity(5) #ma trận có đường chéo là số 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr = np.array([[1,2,3],[4,5,6]])

r = np.repeat(arr,3,axis = 0) # lập theo chiều dọc

print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [21]:
r = np.repeat(arr,3,axis = 1)
print(r)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


In [22]:
np.empty([3,2], dtype = int)

array([[61598480,        0],
       [       0,        0],
       [       0,        0]])

In [23]:
x = np.array([12, 32, np.nan])
x


array([12., 32., nan])

In [24]:
np.all([[True, False],[True, False]])

False

In [25]:
np.any([[True, False],[True, False]])

True

In [26]:
np.all([[1,0],[1,0]])

False

In [27]:
np.all([[1,1],[1,1]])

True