<a href="https://colab.research.google.com/github/VanNguyenThiCam/NumPy-for-Data-Science-Beginners/blob/main/Import_%26_Test_Dimension%2C_Type%2C_Reshape%2C_Size_of_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Sử dụng NumPy***



1.   Arithmetic Operations - Các phép tính toán
2.   Statisticals Operations - Các phép toán thông kê
3.   Bitwise Operators - Toán tử Bitwise 
4.   Copying & viewing arrays - Copy và view ma trận
5.   Stacking - Xếp chồng
6.   Matrix Operations - Tính toán ma trận
7.   Linear Algebra - Đại số tuyến tính
8.   Broadcasting - Broadcasting
9.   Mathematical Operations - Các phép tính toán
10.  Searching, Sorting & Counting 



***Một số import cơ bản***



1.   Kiểm tra version numPy
2.   Tạo ma trận



In [2]:
import numpy as np 

In [3]:
array = np.array([1,2,3,4])
print(array)

[1 2 3 4]


In [9]:
ar = np.arange(6)
print(ar)

[0 1 2 3 4 5]


In [13]:
np.random.randint(2,10) #xuất số ngẫu nhiên trong khoảng 2, 10

4

In [15]:
print(np.__version__) #xem phiên bản numPy đang sử dụng

1.21.6


In [20]:
sample = np.random.randint(0,100,20000000)

%timeit np.power(sample, 2)

10 loops, best of 5: 51.3 ms per loop


In [21]:
%timeit list(np.power(sample, 2)) #kiểm tra thời gian chạy của dòng lệnh

1 loop, best of 5: 1.27 s per loop


***Numpy trong ma trận***



1.   Kiểm tra type, số chiều của ma trận
2.   List item



In [3]:
import numpy as np

arr = np.array([1,2,3,4])

***Type***

In [4]:
print(type(arr)) #kiểm tra loại dữ liệu

<class 'numpy.ndarray'>


***Dimension***

In [6]:
a = np.array(12) #kiểm tra số chiều
print(a.ndim)

0


In [7]:
a = np.array([1,2,3,4])
print(a.ndim)

1


In [17]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a.ndim)

2


***Shape***

In [25]:
a = np.array([[1,2,3,4],[5,6,7,8]])


In [26]:
print(a.shape) #kiểm tra kích cỡ của ma trận a

(2, 4)


In [30]:
a.shape = (4,2) #Cách 1: thay đổi kích cỡ của ma trận a và in ra ma trận theo kích cỡ mới

In [28]:
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
b = a.reshape(2,4) #cách 2 thường dùng hơn
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [31]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[0,11,12]])
print(a.shape)

(4, 3)


In [32]:
b = a.reshape(2,3,2)
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9  0]
  [11 12]]]


In [35]:
arr = b.reshape(-1) #duỗi thành 1 vecto
print(arr)

[ 1  2  3  4  5  6  7  8  9  0 11 12]


***Size***

In [36]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [37]:
arr.itemsize

8

In [40]:
arr = np.array([1,2,3,4], dtype = 'int64') #cách ép kiểu dữ liệu để đưa dữ liệu về cùng 1 loại
print(arr.dtype)

int64


In [41]:
print(arr.size*arr.itemsize)

32


In [42]:
arr = np.array([1,2,3,4], dtype = complex) #chuyển về dạng số thực
print(arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [43]:
arr = np.array([1.1, 2.3, 3.4, 5.5]) #trích lấy phần thực

cv = arr.astype('i')
print(cv)

[1 2 3 5]
