<a href="https://colab.research.google.com/github/VanNguyenThiCam/NumPy-for-Data-Science-Beginners/blob/main/M%E1%BB%99t_s%E1%BB%91_k%C4%A9_thu%E1%BA%ADt_tr%C3%AAn_m%E1%BA%A3ng_ma_tr%E1%BA%ADn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Một số kĩ thuật trên mảng/ ma trận***

1.   index & slice - Chỉ số & cắt lát
2.   Iteration
3.   Array type - Loại mảng/ ma trận
4.   Zero ones - Tạo ma trận toàn số 1
5.   String


name[<font color='green'>start</font>:<font color='blue'>stop</font>:<font color='red'>step</font>]

- index
- slice

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[0]) # xuất ra giá trị ở vị trí 0 
print(arr[1])

1
2


In [2]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)
print(arr[0,1])

print(arr[1,3]) #hàng thứ nhất mang chỉ số 0, cột thứ nhất mang chỉ số 0

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
8


***Ví dụ nâng cao***

In [3]:
arr = np.array([[[1,2,3],[4,6,7]],[[8,9,0],[11,12,13]]])
print(arr)
print(arr.shape) #tensor có 2 chiều, chiều thứ 1 có chỉ số(index) là 0; ở cái chiều thứ 2 chọn vị trí có chỉ số 1,1.
print(arr[1,1,1])

[[[ 1  2  3]
  [ 4  6  7]]

 [[ 8  9  0]
  [11 12 13]]]
(2, 2, 3)
12


In [4]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)
print(arr[1,-1]) #đếm theo chiều thuận thì index bắt đầu là 0. Chiều ngược lại index bắt đầu là -1

[[1 2 3 4 5]
 [6 7 8 9 0]]
0


***Slice***

In [5]:
arr = np.array([1,2,3,4,5,6,7,7,8])
arr[3:7] #cắt từ vị trí thứ 3 đến thứ 7.


array([4, 5, 6, 7])

In [6]:
arr[4:] #từ chỉ số thứ 4 đến cuối


array([5, 6, 7, 7, 8])

In [7]:
arr[:6] # từ chỉ số ban đầu là 0 và kết thúc tại chỉ số thứ 6

array([1, 2, 3, 4, 5, 6])

In [14]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)

arr[0,:] #


[[1 2 3 4 5]
 [6 7 8 9 0]]


array([1, 2, 3, 4, 5])

In [15]:
arr[0,1:3] #chỉ số hàng 0, chỉ số cột bắt đầu từ index 1 và kết thúc trước index 3

array([2, 3])

In [17]:
arr[:,4] # index theo cột 

array([5, 0])

In [24]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,11,12]]])
print(arr)
arr[0,1,2] #lớp chỉ số 0, hàng chỉ số 1, cột chỉ số 2

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 0 11 12]]]


6

In [25]:
arr[:,1,:] #bất chấp lớp, hàng chỉ số 1, bất chấp cột

array([[ 4,  5,  6],
       [ 0, 11, 12]])

In [18]:
arr = np.array([[1,2,3,4,5,6,7,8],[9,0,11,12,13,14,15,16]])
print(arr)
arr[0,1:6:2] #lấy chỉ số hàng 0, bắt đầu từ cột có chỉ số 1 kết thúc chỉ số 6 và cách 2 bước nhảy

[[ 1  2  3  4  5  6  7  8]
 [ 9  0 11 12 13 14 15 16]]


array([2, 4, 6])

***Thay thế một giá trị bất kì***

In [19]:
arr = np.array([[1,2,3,4,5,6,7,8],[9,0,11,12,13,14,15,16]])
print(arr)
arr[0,2] = 2000
print(arr)

[[ 1  2  3  4  5  6  7  8]
 [ 9  0 11 12 13 14 15 16]]
[[   1    2 2000    4    5    6    7    8]
 [   9    0   11   12   13   14   15   16]]


In [20]:
arr = np.array([[1,2,3,4,5,6,7,8],[9,0,11,12,13,14,15,16]])
print(arr)
arr[0,1:4] = 2000
print(arr)

[[ 1  2  3  4  5  6  7  8]
 [ 9  0 11 12 13 14 15 16]]
[[   1 2000 2000 2000    5    6    7    8]
 [   9    0   11   12   13   14   15   16]]


In [21]:
arr = np.array([[1,2,3,4,5,6,7,8],[9,0,11,12,13,14,15,16]])
print(arr)
arr[:,2] = [4000, 5000]
print(arr)

[[ 1  2  3  4  5  6  7  8]
 [ 9  0 11 12 13 14 15 16]]
[[   1    2 4000    4    5    6    7    8]
 [   9    0 5000   12   13   14   15   16]]


In [23]:
arr = np.array([[1,2,3,4,5,6,7,8],[9,0,11,12,13,14,15,16]])
print(arr)
arr[1,:] = [40, 50,60,70,80,90,100,110]
print(arr)

[[ 1  2  3  4  5  6  7  8]
 [ 9  0 11 12 13 14 15 16]]
[[  1   2   3   4   5   6   7   8]
 [ 40  50  60  70  80  90 100 110]]


***Rút theo chỉ số ÂM***

In [31]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
arr[:4]



[1 2 3 4 5 6 7]


array([1, 2, 3, 4])

In [32]:
arr[:-3]

array([1, 2, 3, 4])

In [34]:
arr[::2]

array([1, 3, 5, 7])

In [35]:
arr[arr>3]

array([4, 5, 6, 7])

In [36]:
a = np.array([np.nan,0,1,2,3,4,np.nan])

In [37]:
print(a)

[nan  0.  1.  2.  3.  4. nan]


In [38]:
#mình sẽ áp dụng vào việc xử lý dữ liệu ban đầu, chính là thay thế những vị trí thiếu dữ liệu

a[~np.isnan(a)] #bỏ dữ liệu lỗi ra

array([0., 1., 2., 3., 4.])