<a href="https://colab.research.google.com/github/VanNguyenThiCam/NumPy-for-Data-Science-Beginners/blob/main/To%C3%A1n_Th%E1%BB%91ng_k%C3%AA_Ma_tr%E1%BA%ADn_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Toán thống kê***



1.   Mean
2.   Median
3.   Standard Deviation
4.   Variance
5.   Average
6.   Percentile
7.   Peak to Peak

In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
np.amin(a,0) #lấy số có giá trị nhỏ nhất theo từng cột --> áp dụng trong môn phương pháp tính 

array([1, 2, 3])

In [3]:
np.amin(a,1)

array([1, 4, 7])

In [4]:
np.amax(a,0)# lấy số có giá trị lớn nhất theo từng cột

array([7, 8, 9])

In [5]:
np.amax(a,1)

array([3, 6, 9])

In [6]:
np.ptp(a, 0) #tính range theo cột (max-min)

array([6, 6, 6])

**Nguyên văn chú thích được trích từ numpy.org**

numpy.ptp(a, axis=None, out=None, keepdims=<no value>)
Range of values (maximum - minimum) along an axis.

The name of the function comes from the acronym for ‘peak to peak’.

In [7]:
np.ptp(a,1) #tính range theo cột (max-min)

array([2, 2, 2])

In [8]:
np.percentile(a,50,0) 

array([4., 5., 6.])

***Nguyên văn chú thích được trích từ numpy.org***

numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)

Compute the q-th percentile of the data along the specified axis.

Returns the q-th percentile(s) of the array elements.

In [9]:
np.percentile(a,75,0)

array([5.5, 6.5, 7.5])

In [10]:
np.mean(a)

5.0

In [11]:
np.mean(a,0) # tính mean riêng theo từng cột

array([4., 5., 6.])

In [12]:
np.mean(a,1)

array([2., 5., 8.])

In [13]:
np.median(a)

5.0

In [14]:
np.median(a,0) # tính median riêng theo từng cột

array([4., 5., 6.])

In [15]:
np.median(a,1)

array([2., 5., 8.])

In [16]:
np.average(a,0)

array([4., 5., 6.])

In [17]:
np.average(a,1)

array([2., 5., 8.])

In [18]:
np.std([1,2,3,4])

1.118033988749895

In [19]:
np.var([1,2,3,4])

1.25

***Tạo bộ dữ liệu random***

In [20]:
import numpy as np

x = np.random.randint(0,100)

x

53

In [21]:
x = np.random.randint(0,100,size =(5))
x

array([52, 24, 43, 18, 48])

In [22]:
x = np.random.randint(0,100,size = (3,5))
x

array([[38, 46, 73, 21, 54],
       [61,  4, 35, 76, 29],
       [18, 88, 92, 74, 92]])

In [23]:
x = np.random.rand(3,5)
x

array([[0.48020344, 0.10656548, 0.75142229, 0.24130166, 0.39716144],
       [0.31044738, 0.83814376, 0.34341328, 0.94315443, 0.69294651],
       [0.33249447, 0.84180766, 0.48940242, 0.83252004, 0.5996168 ]])

In [24]:
x = np.random.rand(3,5,4)
x

array([[[9.56892639e-02, 8.62971814e-01, 1.62447006e-01, 6.01234773e-01],
        [7.00016896e-01, 3.21226828e-01, 9.01459013e-01, 6.59697714e-01],
        [3.45951637e-01, 8.67605284e-01, 7.65519912e-01, 7.95824298e-04],
        [7.59455878e-01, 5.94103670e-01, 5.74649514e-01, 8.04521759e-01],
        [8.70985676e-02, 1.69574068e-01, 2.32665125e-01, 6.75827993e-01]],

       [[5.31324337e-01, 5.16103505e-01, 6.94962154e-02, 6.99399468e-01],
        [9.62119120e-01, 5.44335607e-02, 1.32215289e-01, 5.70595989e-01],
        [3.62745166e-01, 6.35949232e-01, 9.87571645e-01, 8.97797115e-01],
        [6.00532608e-01, 1.63580356e-01, 2.26843528e-01, 1.46286352e-01],
        [6.05902759e-02, 2.79035124e-01, 3.91951239e-01, 8.49983219e-01]],

       [[4.99700369e-01, 8.05696439e-01, 1.56120313e-01, 9.52566990e-01],
        [3.19513187e-01, 5.62635954e-01, 9.07617121e-01, 2.29797697e-01],
        [5.05386991e-01, 5.84929237e-01, 4.67663598e-01, 4.65218560e-01],
        [8.30110357e-01, 8.5731671

In [25]:
x = np.random.choice([3,5,7,9], size = (3,5))
x

array([[5, 9, 9, 5, 3],
       [5, 9, 3, 3, 7],
       [3, 3, 9, 3, 7]])

In [26]:
from numpy import random

In [27]:
a = np.array([1,2,3,4,5])

random.shuffle(a)

In [28]:
a

array([3, 2, 1, 4, 5])

In [29]:
random.permutation(a)

a

array([3, 2, 1, 4, 5])

# ***Ma trận trong NumPy***

1.   Sort
2.   Search
3.   Split
4.   Join


***Sort***

1. Xếp lại dữ liệu số theo thứ tự từ nhỏ đến lớn
2. Xếp lại dữ liệu char theo alpha a,b

In [30]:
import numpy as np

a = np.array([3,2,1,8])

np.sort(a)

array([1, 2, 3, 8])

In [31]:
a = np.array(['banana','cherry','apple'])
np.sort(a)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [32]:
a = np.array([True, False, True])

np.sort(a)

array([False,  True,  True])

In [33]:
a = np.array([[3,2,1,8],[6,3,5,4]])

np.sort(a)

array([[1, 2, 3, 8],
       [3, 4, 5, 6]])

***Search***

Tìm kiếm vị trí thỏa theo yêu cầu cho trước 

In [34]:
x = np.array([4,2,4,5,5,4,7]) #tìm những vị trí mà gtri tại đó bằng 4

a = np.where(x == 4)

a

(array([0, 2, 5]),)

In [35]:
a = np.where(x %  2 == 1) #tìm những vị trí mà giá trị tại đó chia 2 dư 1
a

(array([3, 4, 6]),)

In [36]:
x = np.array([8,7,6,9,19]) #

a = np.searchsorted(x,7,side = 'right')

a

3

***Nguyên văn chú thích được trích từ numpy.org***

numpy.searchsorted(a, v, side='left', sorter=None)

Find indices where elements should be inserted to maintain order.

Find the indices into a sorted array a such that, if the corresponding elements in v were inserted before the indices, the order of a would be preserved.




1.  left  a[i-1] < v <= a[i]
2.  right a[i-1] <= v < a[i]



In [37]:
x = np.array([6,7,19,9,8]) # 

a = np.searchsorted(x,9,side = 'left')

a

2

In [38]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2])

***Split***

In [39]:
import numpy as np

a = np.array([1,2,3,4,5,6,7])

x = np.array_split(a,4)

x

[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]

In [40]:
print(x[0])
print(x[1])
print(x[2])

[1 2]
[3 4]
[5 6]


In [41]:
a = np.array([[1,2,3,4,5,6,7]])

x = np.array_split(a,3,axis = 1)
x

[array([[1, 2, 3]]), array([[4, 5]]), array([[6, 7]])]

In [42]:
a = np.array([[1,2,3],[4,5,6]])

x = np.hsplit(a,3)
x

[array([[1],
        [4]]), array([[2],
        [5]]), array([[3],
        [6]])]

In [43]:
x = np.vsplit(a,2)
x

[array([[1, 2, 3]]), array([[4, 5, 6]])]

***Join***

In [49]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])
arr = np.concatenate((x,y))
arr


array([1, 2, 3, 4, 5, 6])

In [53]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
arr = np.concatenate((x,y),axis = 0)
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

arr = np.concatenate((x,y), axis = 1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:
arr = np.concatenate((x,y), axis = 0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [54]:
x = np.array([1,2,3])
y = np.array([4,5,6])

a = np.stack((x,y),axis = 1)
a


array([[1, 4],
       [2, 5],
       [3, 6]])

In [58]:
x = np.array([1,2,3])
y = np.array([4,5,6])

a = np.dstack((x,y))
a

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [59]:
x = np.array([1,2,3])
y = np.array([4,5,6])

a = np.vstack((x,y))
a

array([[1, 2, 3],
       [4, 5, 6]])