<a href="https://colab.research.google.com/github/VanNguyenThiCam/NumPy-for-Data-Science-Beginners/blob/main/To%C3%A1n_Th%E1%BB%91ng_k%C3%AA_Ma_tr%E1%BA%ADn_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Toán thống kê***



1.   Mean
2.   Median
3.   Standard Deviation
4.   Variance
5.   Average
6.   Percentile
7.   Peak to Peak

In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
np.amin(a,0) #lấy số có giá trị nhỏ nhất theo từng cột --> áp dụng trong môn phương pháp tính 

array([1, 2, 3])

In [3]:
np.amin(a,1)

array([1, 4, 7])

In [4]:
np.amax(a,0)# lấy số có giá trị lớn nhất theo từng cột

array([7, 8, 9])

In [5]:
np.amax(a,1)

array([3, 6, 9])

In [6]:
np.ptp(a, 0) #tính range theo cột (max-min)

array([6, 6, 6])

**Nguyên văn chú thích được trích từ numpy.org**

numpy.ptp(a, axis=None, out=None, keepdims=<no value>)
Range of values (maximum - minimum) along an axis.

The name of the function comes from the acronym for ‘peak to peak’.

In [7]:
np.ptp(a,1) #tính range theo cột (max-min)

array([2, 2, 2])

In [8]:
np.percentile(a,50,0) 

array([4., 5., 6.])

***Nguyên văn chú thích được trích từ numpy.org***

numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)

Compute the q-th percentile of the data along the specified axis.

Returns the q-th percentile(s) of the array elements.

In [9]:
np.percentile(a,75,0)

array([5.5, 6.5, 7.5])

In [10]:
np.mean(a)

5.0

In [11]:
np.mean(a,0) # tính mean riêng theo từng cột

array([4., 5., 6.])

In [12]:
np.mean(a,1)

array([2., 5., 8.])

In [13]:
np.median(a)

5.0

In [14]:
np.median(a,0) # tính median riêng theo từng cột

array([4., 5., 6.])

In [15]:
np.median(a,1)

array([2., 5., 8.])

In [16]:
np.average(a,0)

array([4., 5., 6.])

In [17]:
np.average(a,1)

array([2., 5., 8.])

In [18]:
np.std([1,2,3,4])

1.118033988749895

In [19]:
np.var([1,2,3,4])

1.25

***Tạo bộ dữ liệu random***

In [20]:
import numpy as np

x = np.random.randint(0,100)

x

8

In [21]:
x = np.random.randint(0,100,size =(5))
x

array([59,  1, 63, 84, 17])

In [22]:
x = np.random.randint(0,100,size = (3,5))
x

array([[52, 22, 64, 73, 88],
       [10, 51, 44, 98, 26],
       [26, 43, 86, 39, 70]])

In [23]:
x = np.random.rand(3,5)
x

array([[0.08106   , 0.41975942, 0.34729695, 0.00484384, 0.35775784],
       [0.31811787, 0.72710832, 0.00723196, 0.11408068, 0.8807692 ],
       [0.1174525 , 0.46003528, 0.51940147, 0.40289967, 0.70207508]])

In [24]:
x = np.random.rand(3,5,4)
x

array([[[0.90164649, 0.78107964, 0.86595587, 0.39472059],
        [0.41330637, 0.88917546, 0.32340868, 0.80466707],
        [0.3431818 , 0.7702226 , 0.53096123, 0.86535264],
        [0.73336718, 0.32525019, 0.39348691, 0.14844423],
        [0.12947585, 0.43439794, 0.15805743, 0.49487108]],

       [[0.42536951, 0.88310422, 0.64824263, 0.13267301],
        [0.07668783, 0.46051132, 0.1791154 , 0.34104198],
        [0.55033705, 0.89642315, 0.72387392, 0.88838608],
        [0.55508643, 0.01286337, 0.57318292, 0.69327599],
        [0.2469264 , 0.94639271, 0.57524106, 0.62443092]],

       [[0.06586882, 0.68488745, 0.78138   , 0.1443034 ],
        [0.66201616, 0.76798849, 0.95046337, 0.84832195],
        [0.73175932, 0.7220954 , 0.22302914, 0.82748013],
        [0.94174415, 0.00889175, 0.49403809, 0.72890059],
        [0.24290188, 0.6041887 , 0.92481881, 0.09488373]]])

In [25]:
x = np.random.choice([3,5,7,9], size = (3,5))
x

array([[3, 9, 7, 7, 3],
       [3, 3, 3, 7, 9],
       [3, 7, 9, 3, 5]])

In [26]:
from numpy import random

In [27]:
a = np.array([1,2,3,4,5])

random.shuffle(a)

In [28]:
a

array([2, 4, 5, 1, 3])

In [29]:
random.permutation(a)

a

array([2, 4, 5, 1, 3])

# ***Ma trận trong NumPy***

1.   Sort
2.   Search
3.   Split
4.   Join


***Sort***

1. Xếp lại dữ liệu số theo thứ tự từ nhỏ đến lớn
2. Xếp lại dữ liệu char theo alpha a,b

In [30]:
import numpy as np

a = np.array([3,2,1,8])

np.sort(a)

array([1, 2, 3, 8])

In [31]:
a = np.array(['banana','cherry','apple'])
np.sort(a)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [32]:
a = np.array([True, False, True])

np.sort(a)

array([False,  True,  True])

In [33]:
a = np.array([[3,2,1,8],[6,3,5,4]])

np.sort(a)

array([[1, 2, 3, 8],
       [3, 4, 5, 6]])

***Search***

Tìm kiếm vị trí thỏa theo yêu cầu cho trước 

In [34]:
x = np.array([4,2,4,5,5,4,7]) #tìm những vị trí mà gtri tại đó bằng 4

a = np.where(x == 4)

a

(array([0, 2, 5]),)

In [35]:
a = np.where(x %  2 == 1) #tìm những vị trí mà giá trị tại đó chia 2 dư 1
a

(array([3, 4, 6]),)

In [44]:
x = np.array([8,7,6,9,19]) #

a = np.searchsorted(x,7,side = 'right')

a

3

***Nguyên văn chú thích được trích từ numpy.org***

numpy.searchsorted(a, v, side='left', sorter=None)

Find indices where elements should be inserted to maintain order.

Find the indices into a sorted array a such that, if the corresponding elements in v were inserted before the indices, the order of a would be preserved.




1.  left  a[i-1] < v <= a[i]
2.  right a[i-1] <= v < a[i]



In [43]:
x = np.array([6,7,19,9,8]) # 

a = np.searchsorted(x,9,side = 'left')

a

2

In [42]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2])